OUTPUT:
b'\r\n(WERI_cwatm) D:\\Mehdi\\monthly\\CWatM\\Toolkit\\Calibration\\runs_calibration2\\00_045>call C:/Users/psh2610/WERI_cwatm/Scripts/activate \r\nCWATM - Community Water Model  1.5  Date:  21.12.2024  \r\nInternational Institute of Applied Systems Analysis (IIASA)\r\nRunning under platform:  Windows\r\n-----------------------------------------------------------\r\n'
ERRORS:
b'Warning 1: TIFFFetchNormalTag:IO error during reading of "GeoPixelScale"; tag ignored\nWarning 1: TIFFFetchNormalTag:IO error during reading of "GeoTiePoints"; tag ignored\nWarning 1: TIFFFetchNormalTag:IO error during reading of "GeoKeyDirectory"; tag ignored\nWarning 1: TIFFFetchNormalTag:IO error during reading of "GeoDoubleParams"; tag ignored\nWarning 1: TIFFFetchNormalTag:IO error during reading of "GeoASCIIParams"; tag ignored\nWarning 1: TIFFFetchNormalTag:IO error during reading of "GDALMetadata"; tag ignored\nWarning 1: TIFFFetchNormalTag:IO error during reading of "GDALNoDataValue"; tag ignored\nTraceback (most recent call last):\r\n  File "D:\\Mehdi\\monthly\\CWatM\\run_cwatm.py", line 39, in <module>\r\n    main(settings, args)\r\n    ~~~~^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\run_cwatm.py", line 338, in main\r\n    success, last_dis = CWATMexe(settingsfile[0])\r\n                        ~~~~~~~~^^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\run_cwatm.py", line 133, in CWATMexe\r\n    CWATM = CWATModel()\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\cwatm_initial.py", line 166, in __init__\r\n    self.routing_kinematic_module.initial()\r\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\hydrological_modules\\routing_reservoirs\\routing_kinematic.py", line 210, in initial\r\n    report(self.var.catchment,file)\r\n    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\management_modules\\data_handling.py", line 1950, in report\r\n    ds.FlushCache()\r\n    ~~~~~~~~~~~~~^^\r\n  File "C:\\Users\\psh2610\\WERI_cwatm\\Lib\\site-packages\\osgeo\\gdal.py", line 4625, in FlushCache\r\n    return _gdal.Dataset_FlushCache(self, *args)\r\n           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\r\nRuntimeError: TIFFResetField:D:\\Mehdi\\Files\\out_cwatm_30min_khozestan_26Apr\\basin.tif: Can not read TIFF directory entry.\r\n'